[workspace]
members=[
	"nodes_n_procs",
	"nnp_base",
	"nnp_base/nnp_base_core", 
	"nnp_base/nnp_base_runner",
	"nnp_base/nnp_base_runner/runner_macros",
	"nnp_base/nnp_base_runner/runner_deps",
]
default-members=["nodes_n_procs"]

