[package]
name = "nodes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = { default-features = false, version = "1.9.0" }
embedded-hal = "0.2.7"
heapless = "0.7.16"
nb = "1.1.0"
