[package]
name = "nodes_base_runner_deps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.8.0"
nodes_base_nodes = {path= "../../nodes_base_nodes" }
