[package]
name = "nnp_base_runner_deps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.8.0"
nnp_base_core = {path= "../../nnp_base_core" }
