[package]
name = "nnp_base"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nnp_base_core        =  {path="./nnp_base_core"}
nnp_base_runner		= 	{path="./nnp_base_runner"}
